//
// Generated file, do not edit! Created by opp_msgc 4.3 from model/node/applicationLayer/trafficSourceApplication/TrafficSourceControlMessage.msg.
//

#ifndef _TRAFFICSOURCECONTROLMESSAGE_M_H_
#define _TRAFFICSOURCECONTROLMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ControlMessage.h"
// }}



/**
 * Class generated from <tt>model/node/applicationLayer/trafficSourceApplication/TrafficSourceControlMessage.msg</tt> by opp_msgc.
 * <pre>
 * message TrafficSourceControlMessage extends ControlMessage {
 *     type = TRAFFIC_SOURCE_CONTROL_MSG;
 *     int sendToServer;	
 * };
 * </pre>
 */
class TrafficSourceControlMessage : public ::ControlMessage
{
  protected:
    int sendToServer_var;

  private:
    void copy(const TrafficSourceControlMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TrafficSourceControlMessage&);

  public:
    TrafficSourceControlMessage(const char *name=NULL, int kind=0);
    TrafficSourceControlMessage(const TrafficSourceControlMessage& other);
    virtual ~TrafficSourceControlMessage();
    TrafficSourceControlMessage& operator=(const TrafficSourceControlMessage& other);
    virtual TrafficSourceControlMessage *dup() const {return new TrafficSourceControlMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSendToServer() const;
    virtual void setSendToServer(int sendToServer);
};

inline void doPacking(cCommBuffer *b, TrafficSourceControlMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TrafficSourceControlMessage& obj) {obj.parsimUnpack(b);}


#endif // _TRAFFICSOURCECONTROLMESSAGE_M_H_
