//
// Generated file, do not edit! Created by opp_msgc 4.3 from model/packets/DCN_TCPPacket.msg.
//

#ifndef _DCN_TCPPACKET_M_H_
#define _DCN_TCPPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "DCN_IPPacket.h"
// }}



/**
 * Class generated from <tt>model/packets/DCN_TCPPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet DCN_TCPPacket extends DCN_IPPacket
 * {
 *     @customize(true);
 *     kind enum(DCN_EthPacketType) = DCN_TCP_PACKET;
 * 	transportProtocol = IP_PROT_TCP;
 * }
 * </pre>
 *
 * DCN_TCPPacket_Base is only useful if it gets subclassed, and DCN_TCPPacket is derived from it.
 * The minimum code to be written for DCN_TCPPacket is the following:
 *
 * <pre>
 * class DCN_TCPPacket : public DCN_TCPPacket_Base
 * {
 *   private:
 *     void copy(const DCN_TCPPacket& other) { ... }

 *   public:
 *     DCN_TCPPacket(const char *name=NULL, int kind=0) : DCN_TCPPacket_Base(name,kind) {}
 *     DCN_TCPPacket(const DCN_TCPPacket& other) : DCN_TCPPacket_Base(other) {copy(other);}
 *     DCN_TCPPacket& operator=(const DCN_TCPPacket& other) {if (this==&other) return *this; DCN_TCPPacket_Base::operator=(other); copy(other); return *this;}
 *     virtual DCN_TCPPacket *dup() const {return new DCN_TCPPacket(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from DCN_TCPPacket_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(DCN_TCPPacket);
 * </pre>
 */
class DCN_TCPPacket_Base : public ::DCN_IPPacket
{
  protected:

  private:
    void copy(const DCN_TCPPacket_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DCN_TCPPacket_Base&);
    // make constructors protected to avoid instantiation
    DCN_TCPPacket_Base(const char *name=NULL, int kind=0);
    DCN_TCPPacket_Base(const DCN_TCPPacket_Base& other);
    // make assignment operator protected to force the user override it
    DCN_TCPPacket_Base& operator=(const DCN_TCPPacket_Base& other);

  public:
    virtual ~DCN_TCPPacket_Base();
    virtual DCN_TCPPacket_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class DCN_TCPPacket");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};


#endif // _DCN_TCPPACKET_M_H_
