//
// Generated file, do not edit! Created by opp_msgc 4.3 from model/node/applicationLayer/messageApplication/UpdateSendingRateMessage.msg.
//

#ifndef _UPDATESENDINGRATEMESSAGE_M_H_
#define _UPDATESENDINGRATEMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ControlMessage.h"
// }}



/**
 * Class generated from <tt>model/node/applicationLayer/messageApplication/UpdateSendingRateMessage.msg</tt> by opp_msgc.
 * <pre>
 * message UpdateSendingRateMessage extends ControlMessage {
 *     type enum(ControlMessageType) = UPDATE_SENDING_RATE_MSG;
 *     double sendingRate;
 * };
 * </pre>
 */
class UpdateSendingRateMessage : public ::ControlMessage
{
  protected:
    double sendingRate_var;

  private:
    void copy(const UpdateSendingRateMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdateSendingRateMessage&);

  public:
    UpdateSendingRateMessage(const char *name=NULL, int kind=0);
    UpdateSendingRateMessage(const UpdateSendingRateMessage& other);
    virtual ~UpdateSendingRateMessage();
    UpdateSendingRateMessage& operator=(const UpdateSendingRateMessage& other);
    virtual UpdateSendingRateMessage *dup() const {return new UpdateSendingRateMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getSendingRate() const;
    virtual void setSendingRate(double sendingRate);
};

inline void doPacking(cCommBuffer *b, UpdateSendingRateMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, UpdateSendingRateMessage& obj) {obj.parsimUnpack(b);}


#endif // _UPDATESENDINGRATEMESSAGE_M_H_
