//
// Generated file, do not edit! Created by opp_msgc 4.3 from model/node/applicationLayer/messageApplication/UpdateQueueSizeMessage.msg.
//

#ifndef _UPDATEQUEUESIZEMESSAGE_M_H_
#define _UPDATEQUEUESIZEMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ControlMessage.h"
// }}



/**
 * Class generated from <tt>model/node/applicationLayer/messageApplication/UpdateQueueSizeMessage.msg</tt> by opp_msgc.
 * <pre>
 * message UpdateQueueSizeMessage extends ControlMessage {
 *     type enum(ControlMessageType) = UPDATE_QUEUE_SIZE_MSG;
 *     long queueSizePkts;
 *     long queueSizeBytes;
 * };
 * </pre>
 */
class UpdateQueueSizeMessage : public ::ControlMessage
{
  protected:
    long queueSizePkts_var;
    long queueSizeBytes_var;

  private:
    void copy(const UpdateQueueSizeMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdateQueueSizeMessage&);

  public:
    UpdateQueueSizeMessage(const char *name=NULL, int kind=0);
    UpdateQueueSizeMessage(const UpdateQueueSizeMessage& other);
    virtual ~UpdateQueueSizeMessage();
    UpdateQueueSizeMessage& operator=(const UpdateQueueSizeMessage& other);
    virtual UpdateQueueSizeMessage *dup() const {return new UpdateQueueSizeMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual long getQueueSizePkts() const;
    virtual void setQueueSizePkts(long queueSizePkts);
    virtual long getQueueSizeBytes() const;
    virtual void setQueueSizeBytes(long queueSizeBytes);
};

inline void doPacking(cCommBuffer *b, UpdateQueueSizeMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, UpdateQueueSizeMessage& obj) {obj.parsimUnpack(b);}


#endif // _UPDATEQUEUESIZEMESSAGE_M_H_
